### ISSUE TITLE
Integrate Rollbar

### ISSUE THREAD

**Issue by jhash** [WorkHands/RAPiDSkills#241]
https://docs.rollbar.com/docs/javascript

client token: 6c41d7f381264bfcb064f34ad4a98501

**Comment by littleforest** [comment]
@jhash this is how I'm setting the environment on the server:

```
config.environment = ENV["HEROKU_APP_NAME"] || ENV['RAPID_SKILLS_ENVIRONMENT'].presence || 'production'
```

We ended up using the relative URL in the app, since I couldn't get access to the `HEROKU_APP_NAME` environment variable in time. But I think we can access `RAPID_SKILLS_ENVIRONMENT` in the Dockerfile.prod file so then we can at least distinguish between staging and production (review apps will get lumped in with staging).

**Comment by jhash** [comment]
@littleforest where is `RAPID_SKILLS_ENVIRONMENT` defined?

**Comment by jhash** [comment]
@littleforest also, should I be (prep/app)ending something to change the environment to be specific to the frontend?

**Comment by littleforest** [comment]
@jhash it was only defined in Heroku's env vars because I wasn't using it for development, but I just pushed a commit to your branch that sets it in development in the docker vars. You'll have to restart the web service for it to get picked up.
