### ISSUE TITLE
A public user can edit skill descriptions from a cloned skill list for their own standards

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#3]

**Comment by littleforest** [comment]
@Pcushing per our discussion about some occupation standards having skills that are not associated with work processes -- would a standard only have one or the other situation? I.e. be able to determine skills through work processes, OR determine skills directly from `occupation_standard_skills` table? Or is it possible that a standard might have some skills that are derived from work processes as well as some that are not?

**Comment by Pcushing** [comment]
@littleforest we discussed this on the call but just updating here so you can come back to it. I'd assume all of the above are possible -- only competencies, competencies under work processes, and a mix of the two.

**Comment by littleforest** [comment]
@pcushing if a skill is updated to have a new name, then we create a copy of the skill and link it back to the original with the `parent_skill_id` field.  Do we assume that the new copy essentially belongs only to the creator? For example, suppose we have the skill: "Welding", and someone updates the skill to be "Welding Foo". Now suppose another person wants to update "Welding" to "Welding Foo".  Would I have two skill records with description "Welding Foo", both with parent skill id pointing to "Welding"?  Or instead of creating the second copy would I first see if there was already a "Welding Foo" with parent skill "Welding"?

**Comment by littleforest** [comment]
In the case that we have duplicate records, and the creator now wants to make a second change to "Welding Foo Bar", would I change the skill record to "Welding Foo Bar", or create a new skill, with parent skill id pointing to "Welding Foo"?

**Comment by Pcushing** [comment]
We shouldn't have duplicate skill names so someone who changes 'Welding' to
'Welding Foo' should be linked to the previousy created 'Welding Foo'.

**Comment by Pcushing** [comment]
I think that answers the 'Welding Foo Bar' example too?

**Comment by littleforest** [comment]
Yes, thanks.
