### ISSUE TITLE
The system can import occupation standards with skills, work processes, and any other meta we need from a CSV

### ISSUE THREAD

**Issue by Pcushing** [WorkHands/RAPiDSkills#51]
We're going to get a big spreadsheet of occupation standards to import into the system to get started. Let's make sure an admin can just upload that spreadsheet to import from active admin.

Here's an example of one we use with WorkHands that hits some but not all of the fields we'd want to use. 

[acs-occupation.xlsx](https://github.com/WorkHands/RAPiDSkills/files/3677277/acs-occupation.xlsx)

Here's what I think we need to cover in this issue:

1. An admin can get their hands on a template like the above to populate in CSV format.
2. The system has copy that communicates to the admin that they shouldn't change the headers in the template.
3. (Maybe nice-to-have in the early days) but the system can deal with headers that might have extra characters if they opened in excel before saving as CSV.
4. The admin can upload the spreadsheet 
5. The system stores the spreadsheet somewhere for future reference in case there are issues. (Maybe we need a table for this?)
6. The system can analyze the spreadsheet and identify if there are issues with it (missing core data) and communicate that to the admin
7. The system can import all of the occupation standards in the spreadsheet and communicate its completion to the admin

There's many levels of how we get this working with potentially background tasks, emails, new tables, AWS for storage, etc. Let's get the simplest version working possible that'd be expected to be used by a power user (us) with the least infra and fail safes. That likely means doing everything synchronously without storing the files for the long-term.

As soon as we have the preferred format of the spreadsheet, we can marshall resources to get us the spreadsheet so we can start working with real data.

Last, one attr we'll probably want to add to our tables that we dont have already is the `sort_order` as we'll want the ability to sort both work processes and skills. Seems like that'd have to be on the join tables?

**Comment by littleforest** [comment]
Sounds good. Couple questions - 

1. How big is the import file likely to be? Heroku limits requests to 30 seconds, so if it is a huge file, we will run into issues with running it synchronously.  Though we could probably get away with using [Sucker Punch](https://github.com/brandonhilkert/sucker_punch) to run it as a background job for the short term if needed.
3. For (2, 3), if we're not worried about people rearranging the columns, we could not worry too much about the headers, and we can just use the column index to import.
2. For (5), you are thinking maybe create a table with a link to the file (use Active Storage). That table would have its own page in active admin so someone could easily take a look at the file?

I didn't understand what you were meaning about the sort order...? This needs to be saved in a database table, rather than just be sorted on they fly?

**Comment by Pcushing** [comment]
> How big is the import file likely to be? Heroku limits requests to 30 seconds

Yeah. for this first step, i think we just work within the 30s timeout. After that, we'll certainly need sidekiq or something.

> (2, 3), if we're not worried about people rearranging the columns, we could not worry too much about the headers, and we can just use the column index to import.

Given my experience with giving other people a standard spreadsheet and getting one back with new headers / columns / etc., I am worried about them changing the columns. I'm just assuming with a tight group to start, it'll be less of an issue. For 3, I know that when you get a CSV that was converted from excel, the first header description often has some extra non-ascii looking characters in it. Do what feels easiest, but I'd suggest relying on headers more than the index as then we can see if something's changed.

> For (5), you are thinking maybe create a table with a link to the file (use Active Storage). That table would have its own page in active admin so someone could easily take a look at the file?

Yes. It'd be more for us, the engineers, to be able to track down issues. This can be as low tech / low fancy as possible as long as we can debug a file that someone else uploaded.

> I didn't understand what you were meaning about the sort order...? This needs to be saved in a database table, rather than just be sorted on the fly?

Often, these standards have an implied order to them, both for the competencies and work processes. We should store that so we can maintain the order we get from the standards. Reordering would be a separate task at some other point.

**Comment by littleforest** [comment]
@Pcushing in order to have an accurate document upload, I feel like we need more requirements on the related models.  In particular:

* Organization model needs required and unique title
* Industries is optional, but would likely be in this file? If so, can industry be identified by unique naics_code? Or title?
* For work_processes, it would seem that the titles would just have to be unique across occupation_standards, is that correct?
* Similarly for skills, it seems that the descriptions would have to be unique across occupation_standards, but it seems like the description could get modified slightly and then we'd have duplicates. 
* Re issue of duplicates for skills (and possibly work processes), if this file is re-uploaded, would we want to delete all existing work_process and skill connections, and just use the new records?  Or would the upload possibly be adding to existing associations that are already there?

Also:
* Organization Standard is required to have a creator -- would this be something that we would set before we upload the file? I.e. is the whole file upload going to get linked to a single creator? Or do we need to identify the records in the file with a creator?

**Comment by Pcushing** [comment]
Great. Comments inline:

> Organization model needs required and unique title

Agreed.

> Industries is optional, but would likely be in this file? If so, can industry be identified by unique naics_code? Or title?

I honestly dont know how much we're going to get industry at this point. I dont know how to answer this one. It's an optional relationship until we know more.

> For work_processes, it would seem that the titles would just have to be unique across occupation_standards, is that correct?

Correct. 

> Similarly for skills, it seems that the descriptions would have to be unique across occupation_standards, but it seems like the description could get modified slightly and then we'd have duplicates.

Correct. They're unique and there's no good way i know of to know if they're modified slightly to de-dupe. I think we have to assume we'll tease out a manual way to handle this. Now, if they're modified after a clone (#38), we can map to the parent at least.

> Re issue of duplicates for skills (and possibly work processes), if this file is re-uploaded, would we want to delete all existing work_process and skill connections, and just use the new records? Or would the upload possibly be adding to existing associations that are already there?

Good question. In practice, I'm not too worried about whatever we go with bc we're dealing with a linimted group who'd be using this. I lean towards simply including any new records to avoid data loss with the assumption that one can remove work processes / skills manually as needed from there with active admin.

> Organization Standard is required to have a creator -- would this be something that we would set before we upload the file? I.e. is the whole file upload going to get linked to a single creator? Or do we need to identify the records in the file with a creator?

Let's associate with the `current_user` that's logged in for now. We'll likely want the ability to manipulate this in active admin, as what'sl ikely to happen is someone like Kinsey from WIN will do an upload of all skills. Then, if we want to give credit to this individual publicy, we'll need to update it to someone from the actual org that we got the standards from.

**Comment by littleforest** [comment]
@Pcushing coming back to the Creator association on the occupation_standards model (assuming admin is doing the upload)...should the creator field be 

- polymorphic, so that it can accept either a User or AdminUser creator, or
- admin has to select a User, or
- admin may or may not select a User, in which case I need to make the creator field not required.
